### ISSUE TITLE
my cpu is i7 14700kf  Unable to display temperature

### ISSUE THREAD

**Issue by sian0** [LibreHardwareMonitor/LibreHardwareMonitor#1322]
why

**Comment by Z3r10** [comment]
I had the same problem (Surface Pro 7), Temp / Freq stopped working (I had it before though)
It was due to Windows Defender blocking the loading of the driver (LibreHardwareMonitor.sys).

Try to add LibreHardwareMonitor folder to Exclusions:

![image](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/assets/142105919/e04fb3d5-4026-4fa5-8c78-2a2fbba2bc18)
