### ISSUE TITLE
Would it be possible to start using 'HidSharp'

### ISSUE THREAD

**Issue by Fungusware** [LibreHardwareMonitor/LibreHardwareMonitor#166]
'HidSharp' is a .NET Core compatible library that appears to nicely replce the current non-core 'Hid' library.

https://www.nuget.org/packages/HidSharp/

**Comment by Phyxion** [comment]
Possibly, @aquacomputer implemented that for LHM so he might want to take a look at that.

**Comment by MoshiMoshi0** [comment]
Yes, HidSharp is way faster, mainly because HidLibrary checks if the device is connected for each read/write. https://github.com/mikeobrien/HidLibrary/issues/94

But personally I think LibreHardwareMonitorLib should not have any hid/usb library as dependency and all hid code should be somehow moved to LibreHardwareMonitorHid project. It is only used for like 5 very niche devices.
