### ISSUE TITLE
Plan to add VRAM or Hotspot Temps of Graphicscards ? - especially GDDR6X Cards like RTX 3080/3090

### ISSUE THREAD

**Issue by RaptorTP** [LibreHardwareMonitor/LibreHardwareMonitor#440]
Hi,

thanks for this app ! I use it and i already spend some money for this great job.
Now i would like to ask if it is planned to implement more Sensors like HotSpots or VRAM Temps.

My Card has a good cooler and i would like to configure the fans to the VRAM.
The VRAM Temps are NOT linear to the GPU Temps - that´s why it is not possible to set any Offset for example.

Let me know if i can help here in any way.

My card is a Asus RTX 3080 TUF (nonOC)

Thank you and keep up that good work !

**Comment by trankillity** [comment]
Just adding another voice to this request. VRM temps would be incredible as I use this library in combination with the [FanControl](https://github.com/Rem0o/FanControl.Releases) software and would like to do some casual mining when my PC is not being used for gaming, but have to manually override fan speed when doing this due to lack of VRM temperature sensor.

Using a Gigabyte Gaming 3080 OC if it matters.

**Comment by PeggyFree** [comment]
I vote for this feature

**Comment by RaptorTP** [comment]
:) yeah !
Let us know if it helps to read out our sensors or something else to support !

**Comment by Artago** [comment]
VRM, VRAM, and other sensors would be amazing. FanControl is ready to add them as soon as they are available in this project.

**Comment by hsterk** [comment]
> VRM, VRAM, and other sensors would be amazing. FanControl is ready to add them as soon as they are available in this project.

Definitely voltage would be greatly appreciated for those who OC or undervolt.

**Comment by RaptorTP** [comment]
Voltage ?! ... u can easily check and configure with the Curve Editor from MSI AB.

Temp Sensor of VRM + VRAM (and HotSpots) to focus the fan curve on the highest Temps.

**Comment by hsterk** [comment]
> Voltage ?! ... u can easily check and configure with the Curve Editor from MSI AB.
It's for logging metrics while I run benchmarks, not for spot checking but using with ohmgraphite so I can store it in prometheus.

**Comment by RaptorTP** [comment]
got it. But to me it sounds like a seperate issue.
I ask for all temp sensors to choose the hotest (mostly VRAM for those cards) to have the best cooling ;) ans not only for benchmark.

**Comment by JustAMan** [comment]
Hi all, I'm too lazy to port my Python to .NET, but I assume someone who wants this implemented can peek into my pet project: https://github.com/JustAMan/pynvraw/blob/353cc06a9bf6e9e7ab1c67ab73f31182c19bd77b/pynvraw/nvapi_api.py#L293-L314

The function I'm pointing to reads both hotspot and VRAM temperature sensors if they're present (however it's Windows-only due to nvapi usage).

I have tested it on 1080/1080 Ti/Quadro RTX 3000/RTX 3060/RTX 3090 and it reported values very similar to what GPU-z shows.

Hope that helps.

**Comment by RaptorTP** [comment]
hey ! thank you for your effort. So will it implement in future ?
to be honest - i´m too dump for  xD  - otherwise i would help here.

**Comment by JustAMan** [comment]
No idea, I have no interest in porting that for now, my Python package is fine for my needs so far :) And I do not feel up to studying the architecture and whatnot of the LibreHardwareMonitor, just giving some pointers for those who're interested (maybe even core devs).

**Comment by hsterk** [comment]
Does the underlying NVApiWrapper even support the RTX temps? If not, perhaps creating an issue upstream would be more effective?

**Comment by hsterk** [comment]
@RaptorTP The author of NVAPIWrapper(lib used by LibreHardwareMonitor) doesn't have a 30 series card and he's trying to figure out how  the mask input parameter works.  He has a branch where you can run his test program to extract the hotspot/memory temps. I added my EVGA 3080ti FTW results but more cards the better I think.
 https://github.com/falahati/NvAPIWrapper/issues/45

**Comment by northmatt** [comment]
If its for FanControl, just do HWiNFO32 Portable + HWiNFO plugin. You use portable due to having complete shared memory support and 32 so you can run 64 simultaneously with no disabled sensors running at a faster polling rate when you want to look at stuff. Thus 32 can just run in background with temp sensor polling only at a low polling rate.

**Comment by TimSirmovics** [comment]
> 
> 
> @RaptorTP The author of NVAPIWrapper(lib used by LibreHardwareMonitor) doesn't have a 30 series card and he's trying to figure out how the mask input parameter works. He has a branch where you can run his test program to extract the hotspot/memory temps. I added my EVGA 3080ti FTW results but more cards the better I think. [falahati/NvAPIWrapper#45](https://github.com/falahati/NvAPIWrapper/issues/45)

Where are you seeing that NVAPIWrapper is an upstream project for LibreHardwareMonitor?
Looking in the source for Libre it appears that it has it's own implementation calling directly into nvapi64.dll / nvapi.dll: `LibreHardwareMonitor.Interop.NvApi`
I can't find any reference to NVAPIWrapper in this project.

**Comment by lerman01** [comment]
Is there any chance to add this feature to Linux? I know that NvAPI is supported only in Windows, but somehow I know that GMiner figure out how to get the memory temperature in Linux.
